out: 'coverage_out'
buckets: 2
files: 'filtered_assemblies.txt'
split_category: 'spacerLength'
split_collection: [0, 1, 2, 3, 4, 5, 6, 7, 8]
bedtools_path: '/home/dollzeta/frogtools/bedtools2/bin'
mode: 'IR'
gff_parent: 'gff'
extraction_parent: 'irp_out/extracted_accessions'
tempdir: 'coverage_out/temp'
