out: 'coverage_out'
buckets: 100
files: 'filtered_assemblies_2024_3_22.txt'
split_category: 'spacerLength'
split_collection: [0, 1, 2, 3, 4, 5, 6, 7, 8]
bedtools_path: '/storage/group/izg5139/default/nicole/miniconda3/bin'
mode: 'MR'
gff_parent: '/storage/group/izg5139/default/ncbi_database/complete_accessions/2024-03-21_09-07-15/files'
extraction_parent: 'repeat_out'
tempdir: 'coverage_out/temp'
